### ISSUE TITLE
404 File not found Sorry about that

### ISSUE THREAD

**Issue by Sy2n0** [KaindorfCTF/ctfd-notifier#2]
After adding it to plugin, it says that you tried to proceed with the setting, but you couldn't find the file path.
<img width="1792" alt="Screen Shot 2021-12-05 at 7 52 13 PM" src="https://user-images.githubusercontent.com/84657474/144743552-c8f4ff10-dde9-4b4a-a0c0-955770598a76.png">
<img width="1792" alt="Screen Shot 2021-12-05 at 7 52 24 PM" src="https://user-images.githubusercontent.com/84657474/144743557-3fabf619-0add-453f-b5b2-21b574b1f110.png">
<img width="1792" alt="Screen Shot 2021-12-05 at 7 52 33 PM" src="https://user-images.githubusercontent.com/84657474/144743563-8e69b1a8-c7b0-4d86-b12c-da43e2418ab3.png">

**Comment by h4ckd0tm3** [comment]
Issue resolved via DM.

**Comment by KriyenKP** [comment]
Same issue, please post here for everyone else.

**Comment by h4ckd0tm3** [comment]
Essentially as far as I remember, he did not restart the container properly.
So `docker compose down` and `docker compose up -d --build` should do the trick.

**Comment by Sy2n0** [comment]
That's right. Restarting the container fixed it.
